#!/bin/sh
# auto-generated by luban, do not edit
# Rollback script for the luban router config apply/confirm/rollback cycle.
#
# Called by router-rollback.service (oneshot), which fires:
#   1. At boot (OnBootSec=15s) — catches the power-loss case
#   2. 90 s after an apply — the confirm-window expiry
#
# The script is a no-op unless the unconfirmed-apply flag exists.
# /api/confirm removes the flag and stops the timer before this runs.
#
# Invariant: this script NEVER re-renders templates.  A broken template may be
# the very thing being rolled back.  It restores pre-apply backup files directly.

set -eu

FLAG=/opt/router/unconfirmed-apply
OPT=/opt/router

log() {
    echo "luban-rollback: $*" >&2
}

# ── Guard ────────────────────────────────────────────────────────────────────
if [ ! -f "$FLAG" ]; then
    exit 0
fi

log "unconfirmed apply detected — rolling back"

# ── Restore networkd .network/.netdev files FIRST ───────────────────────────
# A bad .network file can take networkd down; restore before reloading so
# networkd comes back with the last-known-good configuration.
#
# Backup scheme: each live generated file has a "<path>.bak" sibling written
# by the Go apply pipeline's installRendered() (router/api/internal/apply/
# pipeline.go) just before it was overwritten. This is the single source of
# truth shared with apply.Rollback() — restore directly from those siblings,
# never from a separate backup tree.
for f in /etc/systemd/network/*.network.bak /etc/systemd/network/*.netdev.bak; do
    [ -f "$f" ] || continue
    dst="${f%.bak}"
    cp -- "$f" "$dst"
    log "restored $dst"
done

# ── Restore other generated configs ─────────────────────────────────────────
restore_file() {
    dst="$1"
    src="$dst.bak"
    if [ -f "$src" ]; then
        cp -- "$src" "$dst"
        log "restored $dst"
    fi
}

restore_file "/etc/nftables.conf"
restore_file "/etc/dnsmasq.d/router.conf"
restore_file "/etc/smartdns/smartdns.conf"
restore_file "/etc/sysctl.d/99-router.conf"
restore_file "/etc/caddy/Caddyfile"
# PPPoE-specific files — only present when PPPoE was the previous WAN mode.
restore_file "/etc/ppp/peers/wan"
if [ -f /etc/ppp/chap-secrets.bak ]; then
    cp -- /etc/ppp/chap-secrets.bak /etc/ppp/chap-secrets
    chmod 600 /etc/ppp/chap-secrets
    log "restored /etc/ppp/chap-secrets"
fi

# ── Restore config.json ──────────────────────────────────────────────────────
if [ -f "$OPT/config.json.bak" ]; then
    cp -- "$OPT/config.json.bak" "$OPT/config.json"
    log "restored config.json"
else
    log "WARNING: config.json.bak missing — cannot restore config source of truth"
fi

# ── Reload kernel parameters ─────────────────────────────────────────────────
sysctl -p /etc/sysctl.d/99-router.conf >/dev/null 2>&1 || true

# ── Reload networkd (must happen before pppd restart) ───────────────────────
# networkctl reload signals networkd to re-read .network files without a full
# restart; it is safe to call even if ppp0 does not yet exist.
networkctl reload || true
# Give networkd a moment to re-match existing interfaces before restarting
# dependent services.
sleep 2

# ── Restart services ─────────────────────────────────────────────────────────
# nftables before everything — restore firewall posture immediately.
systemctl restart nftables       || log "WARNING: nftables restart failed"
systemctl restart systemd-networkd || log "WARNING: networkd restart failed"
systemctl restart dnsmasq        || log "WARNING: dnsmasq restart failed"
systemctl restart smartdns       || log "WARNING: smartdns restart failed"
systemctl restart caddy          || log "WARNING: caddy restart failed"
systemctl restart router-ui      || log "WARNING: router-ui restart failed"
# Restart pppd only if the peers file exists (PPPoE mode).
if [ -f /etc/ppp/peers/wan ]; then
    systemctl restart pppd || log "WARNING: pppd restart failed"
fi

# ── Clear the flag ───────────────────────────────────────────────────────────
rm -f "$FLAG"
log "rollback complete"
