# auto-generated by luban, do not edit
# Caddy runs as root (systemd drop-in overrides the Debian default User=caddy).
# The Go backend listens only on a Unix socket — never on TCP.

{
    # Automatic HTTPS with self-signed cert for internal names.
    local_certs
}

# Catch-all on :443 — deliberately matches ANY Host, not just the named
# sites (router.lan, router, br0.lan, {{ .LanIP }}). This is the repair
# tool for when the network is broken (e.g. reached through an SSH tunnel
# where Host is "localhost"), so it must be reachable no matter what
# hostname the client used to get here. See DECISIONS: "raw LAN IP as
# fallback" — this extends that same rationale to arbitrary hosts.
:443 {
    # on_demand: a hostless site has no static domain list to pick a cert
    # for, so arbitrary/absent SNI needs Caddy to issue one on the fly.
    tls internal {
        on_demand
    }

    # API proxy to the Go backend on its Unix socket. Kept out of the SPA
    # fallback below so a missing API route 404s instead of returning HTML.
    # The backend never listens on TCP; the socket is the only entry point.
    handle /api/* {
        reverse_proxy unix//run/router/api.sock
    }

    # Static frontend assets (built by Vite, fully bundled — no CDN deps).
    # try_files falls back to index.html so React Router paths like
    # /network survive a refresh or direct load instead of 404ing.
    handle {
        root * /opt/router/www
        try_files {path} /index.html
        file_server
    }
}

# Plain-HTTP requests get redirected to HTTPS. A named-host block would
# get this automatically from Caddy; the :443 catch-all above does not,
# so it's spelled out explicitly here.
:80 {
    redir https://{host}{uri} permanent
}
