# auto-generated by luban, do not edit
# PPP CHAP/PAP credentials. This file must be mode 0600.
# WARNING: contains plaintext credentials — exclude from config export/backup.
#
# Format: client  server  secret  ip-addresses
"{{ .WAN.PPPoE.Username }}"  *  "{{ .WAN.PPPoE.Password }}"  *
