# auto-generated by luban, do not edit
# dnsmasq runs as DHCP server only; DNS is handled entirely by SmartDNS.

# Disable dnsmasq's DNS listener; SmartDNS owns :53.
port=0
{{- if .IsBridge }}

# Bridge WAN mode (有线桥): this device is a switch/AP behind an upstream
# router, which is the sole DHCP server on the segment. DHCP is intentionally
# disabled here — dnsmasq keeps running (systemd unit stays enabled) but
# stays inert with no dhcp-range, so it can never race the upstream router
# for DHCP offers.
{{- else }}

# Bind only to the LAN bridge. bind-dynamic avoids the boot race where dnsmasq
# starts before br0 has an address (field-tested; preferred over
# After=systemd-networkd-wait-online@br0.service which can delay boot
# unnecessarily).
interface=br0
bind-dynamic

# Sole authoritative DHCP server on this segment.
dhcp-authoritative

# DHCP pool and lease time.
dhcp-range={{ .LAN.DHCP.Start }},{{ .LAN.DHCP.End }},{{ .LAN.DHCP.Lease }}

# Default gateway: the router itself.
dhcp-option=option:router,{{ .LanIP }}

# DNS server(s) pushed to LAN clients: the router itself (SmartDNS) in auto
# mode, or the user-specified list in manual mode (lan.dhcp.dns_mode).
dhcp-option=option:dns-server,{{ join .DhcpDNSServers "," }}

# Push the .lan search domain so bare names like "router" and "br0" resolve.
dhcp-option=option:domain-search,lan
{{- if ne .MTU 1500 }}

# Advertise the effective WAN MTU via DHCP option 26 (Interface MTU) so LAN
# clients don't send oversized packets. MSS clamp only rescues TCP; large UDP
# (QUIC, WireGuard) is silently dropped without this. Present whenever the
# effective MTU differs from the Ethernet default (PPPoE's fixed 1492, or an
# explicit wan.mtu override), not only for PPPoE.
dhcp-option=option:mtu,{{ .MTU }}
{{- end }}

# Log DHCP transactions to journald.
log-dhcp
{{- end }}
