# auto-generated by luban, do not edit
# Enslaves this LAN port into the br0 bridge.
# Rendered once per LAN interface; .Port is the current interface name.
[Match]
Name={{ .Port }}

[Network]
Bridge=br0
