# auto-generated by luban, do not edit
[Match]
Name=br0

[Network]
# ConfigureWithoutCarrier: an empty bridge has no carrier at boot; without this
# br0 never comes up and dnsmasq cannot bind (field-tested failure mode).
ConfigureWithoutCarrier=yes
{{- if .IsBridge }}
# Bridge WAN mode: this device is a switch/AP behind an upstream
# router. No static address, no delegated-prefix assignment, no RA — br0 is
# a DHCP client on the upstream router's network, same as any other LAN
# client, and upstream RA passes through the bridge unmodified.
DHCP=yes
{{- else }}
Address={{ .LanIP }}/{{ .LanPrefixLen }}
IPv6AcceptRA=no
# Request assignment of a /64 from the delegated prefix to br0.
DHCPPrefixDelegation=yes
# Announce RA to LAN clients so they can use SLAAC.
IPv6SendRA=yes

[IPv6SendRA]
EmitDNS=yes
# Point clients at SmartDNS running on the router.
DNS={{ .LanIP }}
{{- if ne .MTU 1500 }}
# Inform LAN clients of the effective WAN MTU (PPPoE's fixed 1492, or an
# explicit wan.mtu override) so large UDP (QUIC, WireGuard) is not silently
# dropped (MSS clamp only rescues TCP).
MTU={{ .MTU }}
{{- end }}
{{- end }}
