# auto-generated by luban, do not edit
# Applied to ppp0 after pppd brings it up; networkd handles IPv6 RA/DHCPv6-PD.
# IPv4 address comes from IPCP (pppd); IPv6 from RA or DHCPv6 on ppp0.
[Match]
Name=ppp0

[Network]
DHCP=ipv6
IPv6AcceptRA=yes

[DHCPv6]
WithoutRA=solicit
{{- if .Ipv6PrefixLen }}
PrefixDelegationHint=::/{{ .Ipv6PrefixLen }}
{{- end }}
