# auto-generated by luban, do not edit
[Match]
Name={{ .WanIface }}

[Network]
{{- if .WAN.MTU }}
MTUBytes={{ .WAN.MTU }}
{{- end }}
{{- if .IsBridge }}
# Bridge WAN mode: the WAN port joins br0 as a plain bridge port —
# no IP configuration of its own. The upstream router owns DHCP/NAT/RA; br0
# (see networkd-br0.network.tpl) takes the router's management address as a
# DHCP client through the bridge.
Bridge=br0
{{- else if .IsDHCP }}
DHCP=yes
IPv6AcceptRA=yes
{{- else if .IsStatic }}
# IPv4 is statically configured; run DHCPv6 client for prefix delegation only.
DHCP=ipv6
IPv6AcceptRA=yes
Address={{ .WanAddress }}/{{ .WanPrefixLen }}
Gateway={{ .WAN.Static.Gateway }}
{{- range .WAN.Static.DNS }}
DNS={{ . }}
{{- end }}
{{- else if .IsPPPoE }}
DHCP=no
IPv6AcceptRA=no
LinkLocalAddressing=no
{{- end }}

{{- if or .IsDHCP .IsStatic }}

[DHCPv6]
WithoutRA=solicit
{{- if .Ipv6PrefixLen }}
PrefixDelegationHint=::/{{ .Ipv6PrefixLen }}
{{- end }}
{{- end }}
