#!/usr/sbin/nft -f
# auto-generated by luban, do not edit

flush ruleset

{{- if or .IsUnconfigured .IsBridge }}
# ── Unconfigured / Bridge WAN mode ───────────────────────────────────────────
# Unconfigured mode: no WAN port is assigned yet; all ethernet ports are
# enslaved to br0 so the setup wizard is reachable from any port. Only
# LAN-side self-protection rules apply — no masquerade, no MSS clamp, no
# modem SNAT. The forward chain is left ACCEPT (there is no separate WAN
# interface to restrict against).
#
# Bridge WAN mode: the WAN port is bridged into br0; this device is a switch/AP
# behind an upstream router, which owns NAT/masquerade. Same ruleset as
# unconfigured — only self-protection, forward ACCEPT.
define LAN = br0

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;

        # Loopback — always accept.
        iif lo accept

        # Established / related — accept before any drop rules.
        ct state established,related accept

        # Invalid conntrack state — drop immediately.
        ct state invalid drop

        # ICMPv6 ND — the router still needs this for its own management
        # address on br0 (upstream RA/SLAAC passes through the bridge).
        icmpv6 type {
            nd-neighbor-solicit,
            nd-neighbor-advert,
            nd-router-advert,
            mld-listener-query
        } accept

        # DHCPv6 client reply for the router's own management address.
        udp dport 546 accept

        # LAN interface (br0, now including the bridged WAN port) — accept
        # all inbound (admin UI, SSH, …). This is the same "LAN inbound
        # ACCEPT" invariant as routed mode; there is no separate WAN input
        # surface to restrict since WAN is now just another bridge port.
        iifname $LAN accept
    }

    chain forward {
        type filter hook forward priority filter; policy accept;
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}
{{- else }}
# ── Interface aliases ──────────────────────────────────────────────────────────
{{- if .IsPPPoE }}
# PPPoE: the physical WAN port is a bare L2 bearer; all routed traffic flows
# through ppp0.  Both names are defined so rules can reference them explicitly.
define WAN_BEARER = {{ .WanIface }}
define WAN        = ppp0
{{- else }}
define WAN        = {{ .WanIface }}
{{- end }}
define LAN        = br0
define LAN_NET4   = {{ .LanCIDR }}
{{- if .ModemIP }}
define MODEM_IP   = {{ .ModemIP }}
{{- end }}

table inet filter {

    # ICMPv6 neighbor-discovery / MLD types.
    # Required on BOTH the forward chain AND the WAN input chain:
    # - forward:    LAN clients need to reach each other and upstream via SLAAC
    # - WAN input:  the router itself needs upstream RAs for its own IPv6 address
    # Omitting either silently kills SLAAC (field-tested failure mode).
    set nd_icmpv6_types {
        type icmpv6_type
        elements = {
            nd-neighbor-solicit,
            nd-neighbor-advert,
            nd-router-advert,
            mld-listener-query
        }
    }

    chain input {
        type filter hook input priority filter; policy drop;

        # Loopback — always accept.
        iif lo accept

        # Established / related — accept before any drop rules.
        ct state established,related accept

        # Invalid conntrack state — drop immediately.
        ct state invalid drop

        # LAN interface — accept all inbound (admin UI, DHCP, DNS, SSH, …).
        iifname $LAN accept

        # ── WAN input — minimal surface ─────────────────────────────────────

        # ICMPv6 ND on the WAN-facing interface.  The router needs these to
        # receive upstream RAs for its own IPv6 addressing (forwarding=1 would
        # otherwise zero accept_ra; networkd sets accept_ra=2 explicitly, but
        # the firewall must pass these packets through).
        iifname $WAN icmpv6 type @nd_icmpv6_types accept

        # ICMPv6 packet-too-big — rate-limited accept for PMTUD.
        # PPPoE MTU is 1492; without this large IPv6 packets stall silently.
        iifname $WAN icmpv6 type packet-too-big limit rate 100/second accept

        # ICMP echo-request (ping) — rate-limited for debuggability.
        iifname $WAN ip protocol icmp icmp type echo-request limit rate 10/second accept
        iifname $WAN icmpv6 type echo-request limit rate 10/second accept

        # DHCPv6 client reply (udp dport 546).
        # Conntrack never sees this as "established" because the solicit goes to
        # multicast ff02::1:2 but the server replies from unicast.  Source is NOT
        # restricted to fe80::/10: some ISPs reply from a GUA and a source filter
        # silently kills prefix delegation (field-tested).
        iifname $WAN udp dport 546 accept

        # DHCPv4 client reply on physical WAN (DHCP/static modes only).
{{- if not .IsPPPoE }}
        iifname $WAN udp sport 67 udp dport 68 accept
{{- end }}
    }

    chain forward {
        type filter hook forward priority filter; policy drop;

        # Invalid conntrack state.
        ct state invalid drop

        # Established / related — MUST come before the LAN→WAN accept rule.
        # IPv6 has no NAT; without this, IPv6 return packets hit the default
        # DROP and IPv6 connectivity breaks entirely (field-tested failure mode).
        ct state established,related accept

        # ICMPv6 ND in the forward chain — SLAAC dies without this.
        icmpv6 type @nd_icmpv6_types accept

        # ICMPv6 packet-too-big forward — PMTUD for LAN clients.
        icmpv6 type packet-too-big limit rate 100/second accept

        # TCP MSS clamping — mandatory for PPPoE (MTU 1492).
        # PMTUD alone is unreliable: many servers/CDNs drop ICMPv6 too-big,
        # black-holing large TCP sessions silently.
        # "rt mtu" (auto, wan.mss=0) clamps to each route's path MTU; an
        # explicit wan.mss override renders as a fixed value instead.
        tcp flags syn tcp option maxseg size set {{ .MSSClampLine }}

        # LAN → WAN: allow outbound traffic from the LAN.
        iifname $LAN oifname $WAN accept
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}

table ip nat {
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;

        # Masquerade LAN → internet traffic.
        iifname $LAN oifname $WAN masquerade
{{- if .ModemIP }}

        # Masquerade LAN → modem so the modem sees a local source and replies.
        # Without this, the modem (e.g. 192.168.1.1) never routes replies back
        # to LAN clients (field-tested; modem access breaks silently otherwise).
{{- if .IsPPPoE }}
        iifname $LAN ip daddr $MODEM_IP oifname $WAN_BEARER masquerade
{{- else }}
        iifname $LAN ip daddr $MODEM_IP oifname $WAN masquerade
{{- end }}
{{- end }}
    }
}
{{- end }}
