# auto-generated by luban, do not edit
# pppd peer file for PPPoE WAN dialing.
# Run via: pppd call wan nodetach
# Managed by pppd.service (Restart=always, After=systemd-networkd.service).

# Kernel-mode PPPoE plugin (rp-pppoe.so from the ppp package).
plugin rp-pppoe.so

# WAN bearer interface — the physical port running PPPoE frames (no IP configured
# on this interface; all routed traffic flows through ppp0).
{{ .WanIface }}

# PPPoE username — password is in /etc/ppp/chap-secrets (mode 0600).
user "{{ .WAN.PPPoE.Username }}"

# MTU/MRU: 1492 is the standard PPPoE overhead-adjusted value (1500 - 8 byte
# PPPoE header); overridable via wan.mtu.  Must match the value pushed to LAN
# clients via DHCP option 26 and the RA MTU option.
mtu {{ .MTU }}
mru {{ .MTU }}

# Keep trying to reconnect indefinitely (ISP line drops, modem reboots, etc.).
persist
maxfail 0

# Run in foreground so systemd can track the process directly (Type=simple).
nodetach

# Enable IPv6CP negotiation so the ISP can assign an interface identifier;
# the public IPv6 address and prefix are then received via RA/DHCPv6 on ppp0
# (handled by systemd-networkd, not pppd).
+ipv6

# Do not require the peer to authenticate to us (ISP-facing link).
noauth

# Let pppd install the IPv4 default route (IPCP assigns the WAN IP; networkd
# cannot do IPCP, so pppd handles IPv4 addressing and the default route).
defaultroute

# Do NOT push peer DNS into resolv.conf — SmartDNS handles all DNS resolution.
# (Omitting usepeerdns is sufficient; pppd defaults to not pushing peer DNS.)
