# auto-generated by luban, do not edit

# Listen on the LAN bridge address; dnsmasq owns br0:53 is not used (port=0 there).
{{- if .IsBridge }}
# Bridge WAN mode: br0's management address is DHCP-assigned by the
# upstream router and not known at render time, so bind to all interfaces
# rather than a specific address. Local DNS is still useful to LAN clients
# that point at us manually, even though we no longer push it via DHCP
# (the upstream router owns DHCP now).
bind :53
{{- else }}
bind {{ .LanIP }}:53
{{- end }}

# Upstream resolvers.
{{- range .DNSUpstreamLines }}
{{ . }}
{{- end }}

# Response cache.
cache-size 4096
cache-persist yes
cache-file /var/cache/smartdns/smartdns.cache

# Minimum TTL floor (prevents overly short TTLs from thrashing the cache).
rr-ttl-min 60

# Static local records — these names always resolve to the LAN IP.
# .local is deliberately NOT used (RFC 6762 reserves it for mDNS; unicast
# answers for .local confuse Apple devices and Avahi).
{{- if not .IsBridge }}
address /router.lan/{{ .LanIP }}
address /br0.lan/{{ .LanIP }}
{{- end }}
{{- if .ModemIP }}
# Modem access — optical modem behind the WAN port.
address /modem.lan/{{ .ModemIP }}
{{- end }}

# Log to journald via stderr (smartdns -f foreground mode in the systemd unit).
log-console yes
log-level info
