# auto-generated by luban, do not edit
# Kernel tuning for router operation.

# IPv4 forwarding — without this the kernel silently drops forwarded packets.
net.ipv4.ip_forward = 1

# IPv6 forwarding — required for IPv6 routing.
# Side effect: the kernel sets accept_ra=0 on all interfaces when forwarding=1.
# networkd writes accept_ra=2 explicitly on managed interfaces, but this sysctl
# is still declared so manual interface work doesn't silently lose IPv6.
net.ipv6.conf.all.forwarding = 1

# Reverse-path filter (strict mode) — drop packets with spoofed source addresses.
# ppp0 uses mode 2 (loose) below; strict mode is correct for DHCP/static WAN.
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
{{- if .IsPPPoE }}
# PPPoE WAN: ppp0 uses loose rp_filter (mode 2) because some ISPs use
# asymmetric routing where strict mode drops legitimate reply packets.
net.ipv4.conf.ppp0.rp_filter = 2
{{- end }}

{{- if not .IsBridge }}
# Explicit accept_ra=2 on the WAN-facing interface (forwarding=1 would default
# it to 0; networkd also sets this, but declared here for clarity).
{{- if .IsPPPoE }}
net.ipv6.conf.ppp0.accept_ra = 2
{{- else }}
net.ipv6.conf.{{ .WanIface }}.accept_ra = 2
{{- end }}

# Do not accept or send ICMP redirects on the WAN interface.
net.ipv4.conf.{{ .WanIface }}.accept_redirects = 0
net.ipv4.conf.{{ .WanIface }}.send_redirects = 0
{{- else }}
# Bridge WAN mode (有线桥): the WAN port is now a plain br0 bridge port, not
# a routed interface — the accept_ra/redirects tuning above applies to a
# routed WAN link and doesn't make sense here. br0 itself gets its address
# via DHCP (see networkd-br0.network.tpl) and follows normal LAN interface
# defaults.
{{- end }}

# Fair-queue packet scheduler + BBR congestion control for better throughput
# under concurrent flows (especially relevant on PPPoE with limited bandwidth).
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
